name: Deploy using Netlify CLI
        if: ${{ env.deploy_enabled == 'yes' }}
        uses: netlify/actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --site=./dist/site --functions=./dist/functions --prod 
          netlify/actions/cli@mister
  with:
    args: deploy --site=./dist/site --functions=./dist/functions --prod
  env:
    nodejs_version: 20.4.0
    deploy_enabled: yes
    NETLIFY_SITE_ID: ***
    NETLIFY_AUTH_TOKEN: ***
